language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - setup=stable
    - coverage=no

before_script:
  - travis_retry composer self-update
  - composer config discard-changes true
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "psr/log=1.0.0" "php-coveralls/php-coveralls=~2.1" "symfony/yaml=~3.3" --prefer-source --no-interaction --dev; fi

script:
  - if [[ $coverage = 'yes' ]]; then phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then phpunit -c phpunit.xml; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/coveralls -v; fi

matrix:
  include:
    - php: 7.0
      env: setup=coveralls coverage=yes
    - php: 7.1
      env: setup=coveralls coverage=yes
    - php: 7.2
      env: setup=coveralls coverage=yes
